### ISSUE TITLE
Add Argentina to South America countries

### ISSUE THREAD

**Issue by fians4k** [dcealopez/f1-alerts-telegram-bot#1]
No not really an Issue, more like a request. But please can you add Argentina to the South America countries? I think we're in the same  timezone as Sao Paulo, but not entirely sure.

Great work by the way! Very useful bot!

**Comment by dcealopez** [comment]
Hey! Thanks for the suggestion. I just added Argentina to the SA timezones.

If you have any more timezones you would like to see on the session schedule alert do not hesitate to open another issue.
